// Dairo Status — one-time DynamoDB -> D1 seed generator.
//
// The legacy status page lived in a single DynamoDB table (single-table design: every row
// carries an `entity` tag and composite PK/SK keys). This script SCANs that table and emits
// `seed.sql` — a flat list of `INSERT OR REPLACE` statements matching db/schema.sql — which
// you then apply to D1 with:  wrangler d1 execute <db> --file migration/seed.sql
//
// Run locally with AWS credentials (the `dairo-root` profile), e.g.:
//   cd migration && npm i && AWS_PROFILE=dairo-root node migrate.mjs
//
// It is READ-ONLY against DynamoDB and writes exactly one local file (seed.sql).

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, ScanCommand } from "@aws-sdk/lib-dynamodb";

const TABLE = process.env.TABLE || "dairo_status";
const REGION = process.env.AWS_REGION || process.env.REGION || "eu-west-1";
const PAGE_ID = 1; // single public page, slug 'status'
const OUT_FILE = join(dirname(fileURLToPath(import.meta.url)), "seed.sql");

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({ region: REGION }), {
  marshallOptions: { removeUndefinedValues: true },
});

// ── SQL literal helpers ───────────────────────────────────────────────────────────────
/** A quoted, escaped SQL string, or NULL for null/undefined. */
function str(v) {
  if (v === null || v === undefined) return "NULL";
  return `'${String(v).replace(/'/g, "''")}'`;
}
/** An integer/number literal, or NULL. */
function num(v) {
  if (v === null || v === undefined || v === "") return "NULL";
  const n = Number(v);
  return Number.isFinite(n) ? String(n) : "NULL";
}
/** 1/0 from a truthy value. */
function bool(v) {
  return v ? "1" : "0";
}
/** A quoted JSON-array literal from any array-ish value (defaults to []). */
function jsonArr(v) {
  return str(JSON.stringify(Array.isArray(v) ? v : []));
}
/** First non-null/undefined argument (used to prefer explicit attrs, fall back to parsed keys). */
function pick(...xs) {
  for (const x of xs) if (x !== null && x !== undefined) return x;
  return undefined;
}
/** Grab a trailing segment out of a composite sort key like `PC#{order}#{id}` (index from the end). */
function skPart(sk, fromEnd) {
  const parts = String(sk || "").split("#");
  return parts[parts.length - fromEnd];
}

// ── Scan the whole table (paginated) ────────────────────────────────────────────────────
async function scanAll() {
  const items = [];
  let ExclusiveStartKey;
  let page = 0;
  do {
    const out = await ddb.send(
      new ScanCommand({ TableName: TABLE, ExclusiveStartKey }),
    );
    items.push(...(out.Items ?? []));
    ExclusiveStartKey = out.LastEvaluatedKey;
    page += 1;
    console.log(`  scan page ${page}: +${out.Items?.length ?? 0} items (total ${items.length})`);
  } while (ExclusiveStartKey);
  return items;
}

// ── Main ────────────────────────────────────────────────────────────────────────────────
async function main() {
  console.log(`Scanning DynamoDB table "${TABLE}" in ${REGION} ...`);
  const items = await scanAll();

  // Bucket items by their `entity` tag.
  const byEntity = {};
  for (const it of items) {
    const e = it.entity || "unknown";
    (byEntity[e] ||= []).push(it);
  }
  const count = (e) => byEntity[e]?.length ?? 0;
  console.log(
    "Entities:",
    Object.keys(byEntity)
      .sort()
      .map((e) => `${e}=${count(e)}`)
      .join(" "),
  );

  const now = new Date().toISOString();
  const lines = [];
  lines.push("-- Dairo Status seed — generated by migration/migrate.mjs");
  lines.push(`-- Source: DynamoDB table "${TABLE}" (${REGION}) at ${now}`);
  lines.push("-- Apply with: wrangler d1 execute <db> --file migration/seed.sql");
  lines.push("PRAGMA foreign_keys = OFF;");
  lines.push("BEGIN TRANSACTION;");

  const section = (name) => lines.push("", `-- ${name}`);

  // 1) pages ────────────────────────────────────────────────────────────────────────────
  section("pages");
  for (const p of byEntity.page ?? []) {
    lines.push(
      "INSERT OR REPLACE INTO pages " +
        "(id, slug, title, description, icon, homepage_url, contact_url, allow_index, show_uptime, updated_at) VALUES (" +
        [
          PAGE_ID,
          str("status"),
          str(p.title),
          str(p.description ?? ""),
          str(p.icon ?? ""),
          "NULL", // homepage_url
          "NULL", // contact_url
          bool(p.allowIndex),
          bool(p.showMonitorValues),
          str(p.updatedAt ?? now),
        ].join(", ") +
        ");",
    );
  }

  // 2) monitors ──────────────────────────────────────────────────────────────────────────
  // The component-embedded `monitor` map is the richest source, so emit those first and
  // record their ids; then backfill a row for any MON# id that had no component.
  section("monitors");
  const emittedMonitors = new Set();
  const emitMonitor = (m) => {
    if (!m) return;
    const id = Number(pick(m.id));
    if (!Number.isFinite(id) || emittedMonitors.has(id)) return;
    emittedMonitors.add(id);
    lines.push(
      "INSERT OR REPLACE INTO monitors " +
        "(id, name, external_name, url, method, active, created_at, updated_at, deleted_at) VALUES (" +
        [
          id,
          str(m.name ?? m.externalName ?? `monitor-${id}`),
          str(m.externalName ?? m.name ?? `monitor-${id}`),
          str(m.url ?? ""),
          str(m.method ?? "GET"),
          "1",
          str(m.createdAt ?? now),
          str(m.updatedAt ?? now),
          m.deletedAt ? str(m.deletedAt) : "NULL",
        ].join(", ") +
        ");",
    );
  };
  for (const c of byEntity.component ?? []) emitMonitor(c.monitor);
  for (const m of byEntity.monitor ?? []) {
    const id = pick(m.id, skPart(m.PK, 1)); // PK = MON#{id}
    emitMonitor({ ...m, id });
  }

  // 3) monitor_status (from the MON#/#META entities) ──────────────────────────────────────
  section("monitor_status");
  for (const m of byEntity.monitor ?? []) {
    const monitorId = pick(m.id, skPart(m.PK, 1));
    lines.push(
      "INSERT OR REPLACE INTO monitor_status " +
        "(monitor_id, status, last_checked_at, last_code, last_latency_ms) VALUES (" +
        [
          num(monitorId),
          str(m.status ?? "active"),
          m.lastCheckedAt ? str(m.lastCheckedAt) : "NULL",
          num(m.lastCode),
          num(m.lastLatencyMs),
        ].join(", ") +
        ");",
    );
  }

  // 4) components ─────────────────────────────────────────────────────────────────────────
  section("components");
  for (const c of byEntity.component ?? []) {
    const id = pick(c.id, skPart(c.SK, 1)); // SK = PC#{order}#{id}
    const order = pick(c.order, skPart(c.SK, 2));
    lines.push(
      "INSERT OR REPLACE INTO components " +
        "(id, page_id, monitor_id, name, description, sort_order, group_id) VALUES (" +
        [
          num(id),
          PAGE_ID,
          num(c.monitor?.id),
          str(c.externalName ?? c.name),
          c.description ? str(c.description) : "NULL",
          num(order) === "NULL" ? "0" : num(order),
          "NULL", // group_id — groups are intentionally not migrated
        ].join(", ") +
        ");",
    );
  }

  // 5) uptime_daily (rollups) ─────────────────────────────────────────────────────────────
  section("uptime_daily");
  for (const r of byEntity.rollup ?? []) {
    const day = pick(r.day, skPart(r.SK, 1)); // SK = ROLL#{day}
    lines.push(
      "INSERT OR REPLACE INTO uptime_daily (monitor_id, day, ok, total) VALUES (" +
        [num(r.monitorId), str(day), num(r.ok) === "NULL" ? "0" : num(r.ok), num(r.total) === "NULL" ? "0" : num(r.total)].join(", ") +
        ");",
    );
  }

  // 6) incidents ──────────────────────────────────────────────────────────────────────────
  section("incidents");
  for (const inc of byEntity.incident ?? []) {
    const monitorId = pick(inc.monitorId, skPart(inc.SK, 1)); // SK = INC#{monitorId}
    lines.push(
      "INSERT OR REPLACE INTO incidents " +
        "(id, monitor_id, title, summary, status, started_at, resolved_at, auto, created_at, updated_at) VALUES (" +
        [
          num(inc.id),
          num(monitorId),
          str(inc.title),
          str(inc.summary ?? ""),
          str(inc.status ?? "investigating"),
          str(inc.startedAt ?? now),
          "NULL", // resolved_at
          "1", // auto
          str(inc.createdAt ?? now),
          str(inc.updatedAt ?? now),
        ].join(", ") +
        ");",
    );
  }

  // 7) reports (+ updates + affected components) ──────────────────────────────────────────
  section("reports");
  for (const rp of byEntity.report ?? []) {
    lines.push(
      "INSERT OR REPLACE INTO reports (id, page_id, title, status, created_at, updated_at) VALUES (" +
        [
          num(rp.id),
          PAGE_ID,
          str(rp.title),
          str(rp.status ?? "investigating"),
          str(rp.createdAt ?? now),
          str(rp.updatedAt ?? now),
        ].join(", ") +
        ");",
    );
    for (const u of rp.statusReportUpdates ?? []) {
      lines.push(
        "INSERT OR REPLACE INTO report_updates (id, report_id, status, message, date, created_at) VALUES (" +
          [
            num(u.id),
            num(rp.id),
            str(u.status),
            str(u.message ?? ""),
            str(u.date ?? rp.createdAt ?? now),
            str(u.createdAt ?? u.date ?? now),
          ].join(", ") +
          ");",
      );
      for (const uc of u.statusReportUpdateToPageComponents ?? []) {
        lines.push(
          "INSERT OR REPLACE INTO report_update_components (report_update_id, component_id, impact) VALUES (" +
            [num(u.id), num(uc.pageComponentId), str(uc.impact ?? "operational")].join(", ") +
            ");",
        );
      }
    }
  }

  // 8) maintenances (+ affected components) ───────────────────────────────────────────────
  section("maintenances");
  for (const mt of byEntity.maintenance ?? []) {
    lines.push(
      "INSERT OR REPLACE INTO maintenances (id, page_id, title, message, start_at, end_at, created_at, updated_at) VALUES (" +
        [
          num(mt.id),
          PAGE_ID,
          str(mt.title),
          str(mt.message ?? ""),
          str(mt.from ?? now),
          str(mt.to ?? now),
          str(mt.createdAt ?? now),
          str(mt.updatedAt ?? now),
        ].join(", ") +
        ");",
    );
    for (const mc of mt.maintenancesToPageComponents ?? []) {
      lines.push(
        "INSERT OR REPLACE INTO maintenance_components (maintenance_id, component_id) VALUES (" +
          [num(mt.id), num(mc.pageComponentId)].join(", ") +
          ");",
      );
    }
  }

  // 9) subscribers ────────────────────────────────────────────────────────────────────────
  section("subscribers");
  for (const s of byEntity.subscriber ?? []) {
    const token = pick(s.token, skPart(s.SK, 1)); // SK = SUB#{token}
    lines.push(
      "INSERT OR REPLACE INTO subscribers " +
        "(token, email, component_ids, accepted_at, unsubscribed_at, expires_at, created_at, updated_at) VALUES (" +
        [
          str(token),
          str(s.email),
          jsonArr(s.componentIds),
          s.acceptedAt ? str(s.acceptedAt) : "NULL",
          s.unsubscribedAt ? str(s.unsubscribedAt) : "NULL",
          s.expiresAt ? str(s.expiresAt) : "NULL",
          str(s.createdAt ?? now),
          str(s.updatedAt ?? now),
        ].join(", ") +
        ");",
    );
  }

  lines.push("", "COMMIT;", "PRAGMA foreign_keys = ON;", "");

  writeFileSync(OUT_FILE, lines.join("\n"), "utf8");

  console.log(`\nWrote ${OUT_FILE}`);
  console.log(
    "Rows:",
    [
      `pages=${count("page")}`,
      `monitors=${emittedMonitors.size}`,
      `monitor_status=${count("monitor")}`,
      `components=${count("component")}`,
      `uptime_daily=${count("rollup")}`,
      `incidents=${count("incident")}`,
      `reports=${count("report")}`,
      `maintenances=${count("maintenance")}`,
      `subscribers=${count("subscriber")}`,
    ].join(" "),
  );
}

main().catch((err) => {
  console.error("migration failed:", err);
  process.exitCode = 1;
});
